### PR TITLE
Add Coverage support

### PR DESCRIPTION
**Pull request by XhmikosR**
Requires some of the other PRs to be merged

Also, let me know if you want Coveralls or another service and if so add it to the repo before we proceed with this PR.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@MohammadYounes this is ready from my side, please check the OP so that I finish any changes and we land this :)

**Comment by XhmikosR** [comment]
@MohammadYounes do you plan to add Coveralls to the repo? If not, I'll adapt the patch to remove it from actions.

**Comment by MohammadYounes** [comment]
@XhmikosR Coveralls is fine.

**Comment by XhmikosR** [comment]
OK, then you can add Coveralls and merge and it should work.

**Pull request merged**
