### PR TITLE
Add support for `justify-content` property

### PR DESCRIPTION
**Pull request by mbehzad**
i.e. `justify-content: left` <-> `justify-content: right`

### CODE REVIEW

**Comment by MohammadYounes** [comment]
@mbehzad Thank you. However, Flexbox properties follow writing direction and do not require flipping.

> https://github.com/MohammadYounes/rtlcss/issues/33, https://github.com/MohammadYounes/rtlcss/issues/28.

**Comment by mbehzad** [comment]
Hi @MohammadYounes , same could also be said about `padding` when used as e.g. `padding-inline-start: 10px` or `text-align`  in `text-align: start` but as long as they are combined with `left` or `right` keywords (e.g `text-align: left:` or `justify-content: left` (which is a valid option see spec: https://drafts.csswg.org/css-align/#propdef-justify-content)) they don't follow the writing direction but refer to the physical direction.
Therefor I'd like to ask you to reconsider this PR.
cheers

**Comment by MohammadYounes** [comment]
@mbehzad No, the mentioned cases are different. Can you provide an online example showing that `justify-content` does not follow writing direction ?

**Comment by mbehzad** [comment]
Hi @MohammadYounes , sure. Here is a demo: https://jsfiddle.net/hk65cdej/ where you can see that the `justify-content: left` example is always on the left side independent of the writing direction.

**Comment by MohammadYounes** [comment]
@mbehzad Thank you. I believe this applies to `justify-items` too ?

**Comment by mbehzad** [comment]
You are right. the [Spec](https://drafts.csswg.org/css-align/#ref-for-valdef-justify-content-left%E2%91%A0) lists `justify-content`, `justify-self` and `justify-items` as the only flex properties that can have left/right keywords as their values. I have added those other two to the PR as well.

**Pull request merged**
