### PR TITLE
Update CI workflows

### PR DESCRIPTION
**Pull request by XhmikosR**
@MohammadYounes there is a Polynomial regular expression and maybe other issues. This PR should tighten things.

In case you have missed it, you can see the CodeQL issues on https://github.com/MohammadYounes/rtlcss/security/code-scanning (only collaborators can)

Closes #320 while at it

### CODE REVIEW

**Comment by XhmikosR** [comment]
@MohammadYounes there is a Polynomial regular expression and maybe other issues. This PR should tighten checks.

**Comment by XhmikosR** [comment]
@MohammadYounes friendly ping!

See also if you could fix the polynomial regular expression used on uncontrolled data error since it's valid :)

The rest of the new issues, I'm not sure how valid they are, I'll let you decide.

**Comment by MohammadYounes** [comment]
@XhmikosR check the conflicts plz.

**Comment by XhmikosR** [comment]
@MohammadYounes done

**Pull request merged**
