### PR TITLE
package.json: add missing EOF newline

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW @MohammadYounes you should mention some of the fixes in 3.1.0 in the changelog like the potential prototype pollution issue. Not sure if this was present in v2.x but you could issue a security advisory https://github.com/MohammadYounes/rtlcss/security/advisories

FYI there's also a small package size decrease https://packagephobia.com/result?p=rtlcss%403.0.0%2Crtlcss%403.1.0

https://github.com/MohammadYounes/rtlcss/compare/3.0.0...3.1.0?w=1

Anyway, your call of course :)

**Comment by XhmikosR** [comment]
Actually, I'm going to close this PR and keep #217 since `npm` makes this change automatically.

**Comment by MohammadYounes** [comment]
@XhmikosR ok, I'll update the log along with the fix for #218

**Comment by MohammadYounes** [comment]
@XhmikosR [changelog](https://github.com/MohammadYounes/rtlcss/blob/master/CHANGELOG.md) updated. Let me know if you have more suggestions :)

**Pull request closed without merging**
