### PR TITLE
Flip text and border shadows with hex colors too

### PR DESCRIPTION
**Pull request by ocean90**
See added tests in c322d9b. Current test results:

```
1) Mirrored Values (N Value Syntax): Should mirror property value: box-shadow (hex colors):

      AssertionError: 'div { box-shadow: -60px -16px #ff0, 10px 5px 5px #f00, inset 5em 1em 0 #fff; }' == 'div { box-shadow: -60px -16px #ff0, -10px 5px 5px #f00, inset -5em 1em 0 #fff; }'
      + expected - actual

      +div { box-shadow: -60px -16px #ff0, -10px 5px 5px #f00, inset -5em 1em 0 #fff; }
      -div { box-shadow: -60px -16px #ff0, 10px 5px 5px #f00, inset 5em 1em 0 #fff; }

2) Mirrored Values (N Value Syntax): Should mirror property value: box-shadow (hex colors) <REVERESE>:

      AssertionError: 'div { box-shadow: 60px -16px #ff0, -10px 5px 5px #f00, inset -5em 1em 0 #fff; }' == 'div { box-shadow: 60px -16px #ff0, 10px 5px 5px #f00, inset 5em 1em 0 #fff; }'
      + expected - actual

      +div { box-shadow: 60px -16px #ff0, 10px 5px 5px #f00, inset 5em 1em 0 #fff; }
      -div { box-shadow: 60px -16px #ff0, -10px 5px 5px #f00, inset -5em 1em 0 #fff; }

3) Mirrored Values (N Value Syntax): Should mirror property value: text-shadow (hex colors):

      AssertionError: 'div { text-shadow: 1px -1px 0 #fff, 1px -1px 0 #fff, -1px 1px 0 #fff, 1px 1px 0 #fff; }' == 'div { text-shadow: 1px -1px 0 #fff, -1px -1px 0 #fff, 1px 1px 0 #fff, -1px 1px 0 #fff; }'
      + expected - actual

      +div { text-shadow: 1px -1px 0 #fff, -1px -1px 0 #fff, 1px 1px 0 #fff, -1px 1px 0 #fff; }
      -div { text-shadow: 1px -1px 0 #fff, 1px -1px 0 #fff, -1px 1px 0 #fff, 1px 1px 0 #fff; }

4) Mirrored Values (N Value Syntax): Should mirror property value: text-shadow (hex colors) <REVERESE>:

      AssertionError: 'div { text-shadow: -1px -1px 0 #fff, -1px -1px 0 #fff, 1px 1px 0 #fff, -1px 1px 0 #fff; }' == 'div { text-shadow: -1px -1px 0 #fff, 1px -1px 0 #fff, -1px 1px 0 #fff, 1px 1px 0 #fff; }'
      + expected - actual

      +div { text-shadow: -1px -1px 0 #fff, 1px -1px 0 #fff, -1px 1px 0 #fff, 1px 1px 0 #fff; }
      -div { text-shadow: -1px -1px 0 #fff, -1px -1px 0 #fff, 1px 1px 0 #fff, -1px 1px 0 #fff; }
```

### CODE REVIEW

**Comment by ocean90** [comment]
2590eff fixes the issue for me.

**Comment by MohammadYounes** [comment]
The expression is intended to provide safe split over `,` character, which is used in rgb/a and hsl/a color formats. Hex colors need not to be saved before the split (I think it was added by mistake).

To be able to auto-merge this PR, would you please make the following updates:

1. Update the expression : ` "other": /hsl(a?)\(.*?\)|rgb(a?)\(.*?\)/ig,`
2. Update the existing test case to include a hex color shadow, no need to introduce a new one
` 'input': 'div { text-shadow: 10px -8px #ff0, 60px -16px teal, 10px 5px 5px red,inset 5em 1em 0 white;}',`

Thanks.

**Comment by ocean90** [comment]
Thanks for the feedback. 74403eb includes the changes according to your comment.

**Comment by MohammadYounes** [comment]
Fixed in 1.5.1 

Thanks!

**Pull request merged**
