### PR TITLE
A few improvements to the wording

### PR DESCRIPTION
**Pull request by psmears**

### CODE REVIEW

**Comment by MohammadYounes** [comment]
Are you sure about having a colon in the following paragraph ?

When RTLing a CSS document, there are cases where it's impossible to know if the property value should be mirrored or not`:` if the rule selector need to be changed - or a non-directional property has to be updated.

or should it be a comma ?

When RTLing a CSS document, there are cases where it's impossible to know if the property value should be mirrored or not`,` if the rule selector need to be changed - or a non-directional property has to be updated.

Thanks.

**Comment by psmears** [comment]
Hi Mohammad,

Thanks for responding :)

Definitely not just a comma. Reading it again, it actually works better 
with "for example" than a comma:

When RTLing a CSS document, there are cases where it's impossible to
know if the property value should be mirrored or not - for example, if 
the rule selector need to be changed, or a non-directional property has 
to be updated.

Does that seem better to you?

-P

**Comment by MohammadYounes** [comment]
Not sure! They are all examples of impossible cases :

When RTLing a CSS document, there are cases where it's impossible to know:
1. If the property value should be mirrored or not 
2. if the rule selector need to be changed.
3. if a non-directional property has to be updated.

Rephrase the whole paragraph?

**Comment by psmears** [comment]
Ah, I see! I'd misunderstood the meaning. In that case, maybe something 
like:

When RTLing a CSS document, there are cases where it's impossible to 
know whether to mirror a property value, whether to change a rule 
selector, or whether to update a non-directional property.

-P

**Comment by MohammadYounes** [comment]
Cool! I'll merge once you push the change.

**Comment by psmears** [comment]
Thanks. I *think* I've got it right now - I don't have much experience 
with github though, so do check carefully before merging :)

Cheers,

Patrick

**Comment by MohammadYounes** [comment]
Merged. Thanks for contributing to RTLCSS :)

**Pull request merged**
